### PR TITLE
CBBD-134 Fix Orphan FHIR resources

### PR DESCRIPTION
**Pull request by dho937**

### CODE REVIEW

**Comment by dho937** [comment]
@karlmdavis @sbrockhoff  Please review when you get a chance.  Build is failing because of Jenkins server start issues.  Karl just needs to restart Jenkins.  Thanks.

**Comment by sbrockhoff** [comment]
I think I understand the rationale behind some of the changes, but it looks like in some places there is some information that was possibly not carried over (like some of the adjudication entries in `addItemAdjudications()`). Was that a conscious decision to leave out some of those fields?

**Comment by dho937** [comment]
After further analysis, I determined that it wasn't correct to store the amount fields that were at the claim group level at the item level for the Inpatient claim type only.  If we determine that we need to store these claim amounts that are at the group level for this one claim type; then we can do this via extensions if need be.

**Comment by sbrockhoff** [comment]
:+1:

**Pull request merged**
