### PR TITLE
CBBF-30: Ensure that the ITs use mutual SSL auth (and Jetty)

### PR DESCRIPTION
**Pull request by karlmdavis**
This pull request tracks my attempt to implement [CBBF-30: The FHIR server should validate client authentication](http://issues.hhsdevcloud.us/browse/CBBF-30) on the ETL service's side of things using Jetty as the FHIR server's container.

### CODE REVIEW

**Comment by karlmdavis** [comment]
@sbrockhoff and @dho937: Could you please review this? There's a lot of minor refactoring to accommodate the changes I've made, but the bulk of the real work is in `FhirLoader`, `FhirTestUtilities`, and the POMs. Really all this PR is doing is switching the ITs to run Jetty with the production configs that require mutual SSL, and then updating the ETL service to cope with that.

I'm pretty zonked right now, but best as I can tell, all of the major pieces are in place.

The only issue I've noticed is that the HAPI FHIR test webapp (the GUI you see at <http://fhirtest.uhn.ca/>, for example), bombs out with a "`TemplateProcessingException: Exception evaluating SpringEL expression: "conf.rest[0].resource" (tmpl-navbar-left:123)`" error when accessed via HTTPS. This is the same problem that I was initially running into with WildFly. The problem doesn't occur over HTTP, though, which is interesting. Regardless though, that is a problem to be solved in `bbonfhir-server`, not here.

**Comment by karlmdavis** [comment]
(Just a note: the current build failure is due to the JavaDoc problem I mentioned this morning in Dave's inpatient code. I've fixed that locally, and the build passes cleanly for me.)

**Comment by dho937** [comment]
What was the JavaDoc problem I had in my code?

**Comment by dho937** [comment]
I see the JavaDoc error

**Comment by dho937** [comment]
Reviewed at a high level...  :+1:

**Comment by karlmdavis** [comment]
(Just merged in your JavaDoc fix.)

**Comment by karlmdavis** [comment]
Believe I've fixed all of the build problems, and need to close out Sprint 7 ahead of the standup this morning, so merging this.

**Comment by karlmdavis** [comment]
I merged too soon: ended up filing http://issues.hhsdevcloud.us/browse/CBBD-125 to address an interesting problem that didn't show up in my local builds.

**Comment by sbrockhoff** [comment]
:+1:

**Pull request merged**
