### PR TITLE
CBBD-125: Tests failing in second FHIR server execution

### PR DESCRIPTION
**Pull request by karlmdavis**
This PR is designed to resolve [CBBD-125: Tests failing in second FHIR server execution](http://issues.hhsdevcloud.us/browse/CBBD-125), wherein the second module to run Jetty fails because Jetty had never stopped correctly after the first run.

### CODE REVIEW

**Comment by karlmdavis** [comment]
@sbrockhoff and @dho937: Could you please review this PR?

Ultimately, I traced this down to the following bug in the Jetty Maven plugin: https://github.com/eclipse/jetty.project/issues/915. I was able to workaround it by running Jetty in a separate (forked) process, which isn't really a bad idea, anyways.

Please note that the build for this will not pass until https://github.com/HHSIDEAlab/bbonfhir-server/pull/4 is merged.

**Comment by sbrockhoff** [comment]
:+1:

**Comment by dho937** [comment]
:+1:

**Comment by karlmdavis** [comment]
@sbrockhoff and @dho937: Ended up having to make some major changes: switched away from the (broken) Maven Jetty plugin, to instead just use shell scripts that unpack, configure Jetty, and start/stop Jetty.

Happily, this provides two ancillary benefits:

1. Wildfly requires very similar shell scripts, given _its_ broken Maven plugin. Yay for code re-use.
2. The Jetty configuration used in the tests now almost exactly matches the Jetty configs used in AWS.

And... you know, it works...

So there's that.

I'm going to merge this since the build is now passing, but please review the Bash scripts being used when you have a chance.

**Comment by sbrockhoff** [comment]
No concerns here (with the caveat that shell scripts are not necessarily my forte).

**Pull request merged**
