### PR TITLE
Update ITs to automatically deploy "clean" FHIR servers

### PR DESCRIPTION
**Pull request by karlmdavis**
Per [CBBD-40: Update ITs to automatically deploy "clean" FHIR servers](http://issues.hhsdevcloud.us/browse/CBBD-40).

### CODE REVIEW

**Comment by karlmdavis** [comment]
@sbrockhoff and @dho937: Can you guys please review this?

Note: the failing build is due to Jenkins being low on space. I'm working to fix that.

**Comment by sbrockhoff** [comment]
Hey Karl - I was trying to just run bluebutton-data-pipeline-fhir-load as a maven build by itself, but get dependency issues with the other modules since I apparently haven't done a maven install on the full bluebutton-data-pipeline project before. 

When attempting to build the entire thing, I run into issues with the de-synpuf data, which I remember removing locally before because I think the files were being imported into the wrong location in my local workspace? My memory is a little fuzzy on that.

Here's an example of the error I see below. I don't think I actually even have the synpuf files locally at this point and i'm not sure exactly how to bring them in. I do have GitLFS installed locally.

For now i'm going to ignore the synpuf tests locally to try to get past this issue. 
```
Tests run: 5, Failures: 0, Errors: 3, Skipped: 2, Time elapsed: 0 sec <<< FAILURE! - in gov.hhs.cms.bluebutton.datapipeline.sampledata.SampleDataLoaderTest
spotCheckBeneficiaryFromSampleTestA(gov.hhs.cms.bluebutton.datapipeline.sampledata.SampleDataLoaderTest)  Time elapsed: 0 sec  <<< ERROR!
gov.hhs.cms.bluebutton.datapipeline.desynpuf.SynpufException: java.io.IOException: Stream is not in the BZip2 format
	at gov.hhs.cms.bluebutton.datapipeline.sampledata.SampleDataLoaderTest.spotCheckBeneficiaryFromSampleTestA(SampleDataLoaderTest.java:72)
Caused by: java.io.IOException: Stream is not in the BZip2 format
	at gov.hhs.cms.bluebutton.datapipeline.sampledata.SampleDataLoaderTest.spotCheckBeneficiaryFromSampleTestA(SampleDataLoaderTest.java:72)
```

**Comment by sbrockhoff** [comment]
The other issue I am running into is that bluebutton-data-pipeline-fhir-sampledata is trying to run "chmod" as part of the capsule-maven-plugin which doesn't exist on Windows.

`[ERROR] Failed to execute goal com.github.chrischristo:capsule-maven-plugin:1.0.1:build (default) on project bluebutton-data-pipeline-fhir-sampledata: Cannot run program "chmod": CreateProcess error=2,`

**Comment by sbrockhoff** [comment]
The good news is the FhirLoaderIT did run for me. It took about 20 minutes to run on my machine.

**Comment by karlmdavis** [comment]
Can you file a defect for the capsule problem?

**Comment by sbrockhoff** [comment]
For the content of this commit specifically, I don't have any concerns - looks good to me! Was nice to be able to spin up the HAPI server and see it in action. I was able to use the instructions provided to run command line and also inside Eclipse. :+1:

**Comment by karlmdavis** [comment]
This took way too many commits to get passing on Jenkins, but it's finally passing. Merging.

**Pull request merged**
